CREATE TABLE IF NOT EXISTS User (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username VARCHAR (64) NOT NULL UNIQUE,
    email VARCHAR (120) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR (32) NOT NULL,
    password_hash VARCHAR (256)
);